### ISSUE TITLE
Gender Prediction Methods Based on Name

### ISSUE THREAD

**Issue by Hamedloghmani** [fani-lab/Adila#36]
Hello @gabrielrueda,
You have been added to this repo and you can log and discuss your process here from now on as well as Trello.

**Comment by gabrielrueda** [comment]
@Hamedloghmani 

Here are observations that I mentioned about earlier. These observations are some of the inconsistencies that occur when names are represented in the dataset. 

Case 1) The dataset shows "DuarteCesar" but on dblp the actual name is "Cesar Duarte"
Case 2) The dataset shows "A AbramovSergei" but on dblp the actual name is "Sergei A. Abramov" 
Case 3) The dataset show "A A Aoude" but there's multiple results on dblp (no first name given it seems) 
Case 4) The dataset shows "M. Turunen" but M is just the first letter of the first name


I looked into a few names like case 1 and case 2 and there seems to be a pattern, that when there is no space between the names, the order for first name, last name is reversed. I was wondering if I could implement something in the code to detect that and assume case 1 and case 2. As for case 3 and 4, I was thinking I could just discard those. 

--- 

My idea to deal with these cases:

Pass Through 1:
1. Create new json file(e.g. dblp_correctNames.json)
2. If the name is successful in finding first name using regular method (FIRSTNAME SPACE LASTNAME), that json row is copied to the dblp_correctNames.json file. 
3. If the name follows case (1) or case (2), then the name will be modified and also copied to the dblp_correctNames.json file. 
4. Otherwise, if the name follows case (3) or case (4), those will be copied to another json file (dblp_failed_to_parse_name.json), where they could possibly be used for future if needed.

Pass Through 2:
1. Will go through dblp_correctNames.json and record all unique names as originally intended. They will be recorded in an indexed pandas dataframe with empty columns of "Gender" and "Probability" 


I will let you know when I implement this idea in code and I'll share the results.

**Comment by Hamedloghmani** [comment]
@gabrielrueda 
Thank you so much for your progress report.

As we discussed, your idea was great based on the observations that you had.
Thank you, looking forward to seeing the implementation and results 😄

**Comment by gabrielrueda** [comment]
Hello @Hamedloghmani, 

After running the filter on the intitial dataset, and then finding all the unique first names, the program found 275 896 unique first names in the filtered dataset (Removing Cases 3 & 4 as well modifying cases 1 & 2). 

I have made a pull request (#59) to include the code. Also I have included the results as a uniquenames_filtered.pkl and uniquenames_filtered.csv files (uniquenames_filtered.pkl is there to preserve the index I setup on the pandas dataframe). 

I also have the json files for dblp_correctNames.json and dblp_failed_to_parse.json. I can send these privately since the files are too large to be pushed to git. 

Let me know if you have any questions.

**Comment by Hamedloghmani** [comment]
Thank you so much for the update @gabrielrueda 
I'll go over your code and results today. We'll start labeling after I merge this request and refactor it.
I'll keep you posted.
You can upload the large results in Teams -> Adila -> DBLP Labeling Files
Thanks.

**Comment by gabrielrueda** [comment]
Hello @Hamedloghmani,
I filled in the table for genders of each unique name, The table will be stored as both a .pkl and .csv, but use the .pkl to import data into the program just like the uncommented lines in the main function. 

I basically completed two steps in order to  obtain data:
1. Made http requests to get the data from genderize and outputted the whole thing to a text file. (I have the text files on my computer if your interested) -> makeParallelAPIReqs()
2. Read from those text files and updated the values in the dataframe -> addGenderResultsFromFile()

I left some of things commented at the bottom, since for a chunk of the data (between records 90k and 160k), I obtained the data in a different way, however for future use, the functions in class should be used.

**Comment by Hamedloghmani** [comment]
Hi @gabrielrueda 

Thank you so much for the update. I'll take a look and get back to you asap for the final step.

**Comment by gabrielrueda** [comment]
@Hamedloghmani 
I think that we are ready to label the whole dataset. Also, some of the entries will result in NULL for gender/probability. Should we just filter out those entries when creating our new dataset?

**Comment by Hamedloghmani** [comment]
@gabrielrueda 
Great !
Yes, I believe we can filter them out.

**Comment by gabrielrueda** [comment]
@Hamedloghmani 
Also, would a structure like this: "gender": {"value": true, "probability": 0.97} for each author be good to represent the values in the dataset?

Example:
{"id":1,"authors":[{"name":"Hinton",**"gender": {"value": true, "probability": 0.97}**,"org":"Shinshu University","id":1},{"name":"LeCun",**"gender": {"value": false, "probability": 0.87}**,"org":"Shinshu University","id":3}],"fos":[{"name":"Machine Learning","w":0.45139},{"name":"Image Captioning", "w":0.3241}],"title":"Preliminary Design of a Network Protocol Learning Tool Based on the Comprehension of High School Students: Design by an Empirical Study Using a Simple Mind Map","year":2000,"n_citation":1,"page_start":"89","page_end":"93","doc_type":"Conference","publisher":"Springer, Berlin, Heidelberg","volume":"","issue":"","doi":"10.1007/978-3-642-39476-8_19","references":[2005687710,2018037215],"indexed_abstract":{"IndexLength":58,"InvertedIndex":{"tool.":[42],"study":[4],"aim":[37],"purpose":[1],"scientific":[17],"for":[11],"aspects":[18],"students":[14,46],"focus":[27],"hands-on":[47],"learning":[9,41],"experience":[48],"our":[40],"we":[26],"network":[33,56],"The":[0],"More":[24],"high":[12],"protocols.":[57],"school":[13],"and":[21],"of":[2,19,32,55],"communication":[22],"protocols":[34],"gives":[45],"on":[28],"a":[8],"studying":[15],"specifically,":[25],"this":[3],"understand":[51],"is":[5],"develop":[7,39],"Our":[43],"tool":[10,44],"the":[16,29,36,52],"help":[50],"as":[35],"principles":[31,54],"information":[20],"networks.":[23],"to":[6,38,49],"basic":[30,53]}},"venue":{"raw":"International Conference on Human-Computer Interaction","id":1127419992,"type":"C"}}

**Comment by Hamedloghmani** [comment]
@gabrielrueda 
Yes. I think that's great since we might need to use inferred genders with specific levels of confidence in some cases.

Thanks.

**Comment by gabrielrueda** [comment]
Hi @Hamedloghmani,
I just wanted to let you know that I labelled the dataset, and kept all the successful entries (entries whose name could successfully a gender). I will create a pull request for the code. Where should I upload the labelled dataset (since it's too big to upload to GitHub)?

**Comment by Hamedloghmani** [comment]
Hello @gabrielrueda 
Thank you so much for the update. I'll go over your pull request tonight.
Please upload them in MS Teams -> Adila -> DBLP Labeling Files
You can create another folder inside this directory if you want. I can reformat it later, no worries.

Let me know if you run into any issues.
Thanks

**Comment by gabrielrueda** [comment]
@Hamedloghmani 
The dataset finished uploading. It should be in MS Teams -> Adila -> DBLP Labeling Files -> FinalGenderLabelledDataset. Let me know if you are unable to see/access it.

Thanks

**Comment by Hamedloghmani** [comment]
@gabrielrueda 
Thank you Gabriel. I just checked and I got access to it.

**Comment by gabrielrueda** [comment]
Hi @Hamedloghmani ,
I finished labelling the dataset, but I filtered some of the members from the name.basics.tsv file. Since I filtered out the names, should I update the title.basics.tsv and title.principals.tsv files to remove the entries that include the names that I filtered out in the labelling process?

**Comment by Hamedloghmani** [comment]
Hello @gabrielrueda 
Thank you so much for the update. You can consider doing that if it is not too time consuming.
In the next steps we would discuss mapping the names from the OpeNTF outputs to the raw dataset and also a policy for missing names.
I will schedule a meeting to talk about that soon if you want.

**Comment by gabrielrueda** [comment]
Hello @Hamedloghmani,
It shouldn't be time consuming to filter it out in the other files, so I'll do that and let you know when I complete it. As for the next task, yes it would be great to schedule a meeting for that.

**Comment by gabrielrueda** [comment]
Hi @Hamedloghmani,
I finished filtering the entries in title.basics.tsv and title.principals.tsv in order to match what was filtered in the names.basics.tsv file. These 3 files are uploaded to the "IMDB Labelling Files" folder. I'll make a pull request tomorrow for the code, I just have to add comments and rename some of the functions.

**Comment by Hamedloghmani** [comment]
Hello @gabrielrueda 
Thanks a lot for the update. 
Please make the pull request on the _**main**_ branch this time. Including your previous implementations for dblp.

Thank you

**Comment by gabrielrueda** [comment]
Hi @Hamedloghmani,
I just created the pull request for the code. 

Thanks, Gabriel

**Comment by Hamedloghmani** [comment]
Hello @gabrielrueda 
I merged your pull request. Thanks a lot.

**Comment by gabrielrueda** [comment]
Hello @Hamedloghmani,

Here is the approach I will take to map the indexes from OpeNTF to the raw dataset:

#### Part 1:
In the indexes.pkl there is the 'i2c' and 'c2i' dictionaries:

Example:
```
'i2c': {
    9 : '54977.0_Reginald_Barker'
}
```
```
c2i: {
	'54977.0_Reginald_Barker' : 9
}
```
	 
The string '54977.0_Reginald_Barker' will include the member id from the raw dataset **before the '.''**
In this case it would be 54977

#### Part 2: 
However, in the name.basics.tsv file, the member id would be listed as 'nm0054977'.

The member id has the layout of "nm" + 7 digits.

e.g. 54977 would be 'nm0054977'

(add 0's in unassigned digits)


#### Part 3: The mapping:
1. Loop through 'c2i' dictionary and create new dictionary with layout as described in part 2. `{memberID: opeNTF_output_index}`
2. Create a pandas dataframe: (make sure to set opeNTF_output_index as the index)

| opeNTF_output_index | gender            | probability                      |
| ------------------- | ----------------- | -------------------------------- |
| (integer)           | (true/false/null) | (double from 0.0 to 1.0 or null) |

> true = male, false = female

3. Loop through name.basics_labelled.tsv. For each member id, find the index using the dictionary created in step 1. Add the opeNTF_output_index and the gender/probability from the file to the new dataframe.
4. Then, loop through the list of keys from 'i2c'. If the opeNTF_output_index is not in the pandas dataframe, the add that opeNTF_output_index with gender as null and probabilty as null.
5. Export the dataframe as .csv and .pkl for future use.

**Comment by Hamedloghmani** [comment]
Hi @gabrielrueda 
Thank you so much for your report. The approach makes sense as we discussed. You can proceed with the implementation.

Thanks

**Comment by gabrielrueda** [comment]
Hi @Hamedloghmani,
I finished the implementation. Should I make a pull request for my implementation to the dev or main branch?

Thanks, Gabriel

**Comment by Hamedloghmani** [comment]
Hi @gabrielrueda 
Thank you so much for the update. Make it to the main branch please.

Thanks

**Comment by gabrielrueda** [comment]
Hello @Hamedloghmani,

I just wanted to let you know that I changed the true/false in the dataset to M/F, as well as updated the results in mapping table for IMDB. I also created a mapping table for DBLP. 

In the pull request I updated the mappingGender.py and labelDataset.py for the changes needed. I have also included the file called changeDataset.py, which I only used as a temporary way to change the values to true/false to M/F.

Finally, the updated datasets and mapping tables will be uploaded to the Teams Adila channel in folders of DBLP Labelling Files/Gender Mappings and IMDB Labelling Files/Gender Mappings (I'll let you know when they finish uploading).
